# Generated by Django 4.0.5 on 2022-06-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=250)),
                ('college_year', models.SmallIntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year'), (5, 'Fifth Year'), (6, 'Sixth Year'), (7, 'Masters Degree'), (8, 'Phd')])),
                ('birthday', models.DateField()),
                ('college_major', models.CharField(max_length=500)),
                ('review_count', models.SmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
