# Generated by Django 4.0.4 on 2022-06-05 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('test1', '0004_remove_user_details_id_alter_user_details_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='professor_details',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('professor_name', models.CharField(max_length=250)),
                ('University_name', models.CharField(max_length=250)),
                ('Department', models.CharField(max_length=250)),
                ('Avg_Rating', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.AlterField(
            model_name='user_details',
            name='college_year',
            field=models.SmallIntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year'), (5, 'Fifth Year'), (6, 'Sixth Year'), (7, 'Masters Degree'), (8, 'Phd'), (9, 'Professor')]),
        ),
    ]
