# Generated by Django 4.0.5 on 2022-06-05 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test1', '0005_professor_details_alter_user_details_college_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('post_title', models.CharField(max_length=250)),
                ('post_content', models.TextField()),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_time', models.DateTimeField()),
                ('posts_comments', models.JSONField(blank=True)),
                ('posts_likes', models.IntegerField(default=0)),
                ('posts_dislikes', models.IntegerField(default=0)),
                ('posts_report', models.CharField(blank=True, max_length=250)),
                ('posts_report_description', models.TextField(blank=True)),
                ('user_id', models.ForeignKey(default='no_user', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_title', models.CharField(max_length=250)),
                ('review_details', models.TextField()),
                ('review_comments', models.JSONField(blank=True)),
                ('course_name', models.TextField()),
                ('review_time', models.DateTimeField()),
                ('review_rating', models.IntegerField()),
                ('review_likes', models.IntegerField(default=0)),
                ('review_dislikes', models.IntegerField(default=0)),
                ('review_report', models.CharField(blank=True, max_length=250)),
                ('review_report_description', models.TextField(blank=True)),
                ('user_id', models.OneToOneField(default='no_user', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user_details',
            name='Avg_Rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Department',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user_details',
            name='recent_comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='recent_posts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='university_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='college_major',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='review_count',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='professor_details',
        ),
    ]
